# Generated by Django 3.1.7 on 2021-03-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoriyName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChastnoLitso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrivatePersonName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Dogovornaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DogovornayaName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Edinitsva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EdinitsvaName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nalichie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NalichieName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sostayanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SostayanieName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserNameOne', models.CharField(choices=[('1', 'Jismoniy shaxs'), ('2', 'Yuridik shaxs')], max_length=50)),
                ('UserNameTwo', models.CharField(max_length=50)),
                ('UserEmail', models.EmailField(max_length=100)),
                ('UserPassword', models.CharField(max_length=100)),
                ('UserPhone', models.CharField(max_length=100)),
                ('UserOferta', models.BooleanField(blank=True, choices=[('1', True), ('2', False)], max_length=50)),
                ('UserTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegName', models.CharField(max_length=100)),
                ('RegPro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sort', to='AgroApp.province')),
            ],
        ),
        migrations.CreateModel(
            name='Obyavleniya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obyavName', models.CharField(max_length=100)),
                ('categry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AgroApp.categoriya')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=1000)),
                ('Stoim', models.FloatField(max_length=20)),
                ('OpisaniyaName', models.TextField()),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AgroApp.categoriya')),
                ('Dogovr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AgroApp.dogovornaya')),
                ('Litso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AgroApp.chastnolitso')),
                ('Nalich', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AgroApp.nalichie')),
                ('Obyav', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AgroApp.obyavleniya')),
                ('Regions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AgroApp.province')),
                ('Sosta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AgroApp.sostayanie')),
                ('Sum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AgroApp.edinitsva')),
            ],
        ),
    ]
