# Generated by Django 3.1.7 on 2021-03-11 14:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(null=True, upload_to='news_image'), default=[], size=None),
        ),
    ]
